### ISSUE TITLE
Would be nice if matalign checked for compatible matrices

### ISSUE THREAD

**Issue by bpolacco** [jianhong/motifStack#10]
It appears that matalign assumes the pfm/pcm have the same row structure (same number of rows and labels in the same order). Depending on how a pfm/pcm is constructed this may not always be true.  I ran into this with AA motifs with code similar to this (with oversimplified motifs) that relied on `Biostrings::consensusMatrix` to construct my pfm matrices: 

```
motifs <- list( c( "SLQRSDSSQPMLL"), c("QPMLLNTPAPVPP" ), c("AGTPIDSSQPMLL", "SLQRSDSSQPMLL" ))

pfms <- lapply(motifs, function(m)new("pfm", Biostrings::consensusMatrix(m, as.prob = TRUE), name = m[[1]]))
motifStack::motifStack(pfms, layout = "tree") 
# alignment quietly fails except for some numerous but mysterious warnings
``` 
![image](https://user-images.githubusercontent.com/47793553/133516396-872ae05d-41ac-4199-b2ee-78c43579f685.png)

I can fix this (once I recognized the problem) as below, but it would be a nice feature of your method to check its assumptions of equivalent matrix rows and maybe order (when row names are present).

```
fullAAConsensusMatrix <- function(seqs){
  aaLetters <- c("A", "C", "D", "E", "F", "G", "H", "I", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "Y")
  cm <- Biostrings::consensusMatrix(seqs, as.prob = TRUE )
  missingAA <- setdiff(aaLetters, rownames(cm))
  if (length(missingAA) > 0){
    missingRows <- matrix(0, nrow = length(missingAA), ncol = ncol(cm), dimnames = list(missingAA, NULL) )
    cm <- rbind (cm, missingRows)
  }
  # enforce consistent order:
  return (cm[aaLetters,])
}

pfms <- lapply(motifs, function(m)new("pfm", fullAAConsensusMatrix(m ), name = m[[1]]))
motifStack::motifStack(pfms, layout = "tree")

```
![image](https://user-images.githubusercontent.com/47793553/133516446-ae354777-b867-4044-aca9-2a9fe2bb1212.png)

Thanks again!

**Comment by jianhong** [comment]
Thank you for reporting. It was fixed in 1.37.4
