### ISSUE TITLE
Error in pfms[[getPFMid(pfms, .name, rcpostfix = rcpostfix)]]

### ISSUE THREAD

**Issue by mdozmorov** [jianhong/motifStack#11]
I'm following the vignette [plot a sequence logo cloud](https://www.bioconductor.org/packages/devel/bioc/vignettes/motifStack/inst/doc/motifStack_HTML.html#plot_a_sequence_logo_cloud), the example works. Trying the same with my motifs fails at the `motifSignature` function with error:
```
Error in pfms[[getPFMid(pfms, .name, rcpostfix = rcpostfix)]] : 
  attempt to select less than one element in get1index
```
I went down the `motifSignature` and `getPFMid` code but couldn't solve it within a reasonable time. Please, advice, code to reproduce:
[pfms1.RData](https://drive.google.com/file/d/1uKzYXonOEYs-Jy3_RHA_THwQayuVWAby/view?usp=sharing)
````{r}
library(motifStack)
load(file = "pfms1.RData")
pfms1 <- motifs_all[1:10]
## use matalign to calculate the distances of motifs
hc <- clusterMotifs(pfms1)
## convert the hclust to phylog object
library(ade4)
phylog1 <- ade4::hclust2phylog(hc)
## reorder the pfms1 by the order of hclust
leaves <- names(phylog1$leaves)
pfms1 <- pfms1[leaves]
## extract the motif signatures
motifSig <- motifSignature(pfms1, phylog1, cutoffPval=0.0001, min.freq=1)
````

**Comment by jianhong** [comment]
Did you tried to rename your motifs with safe characters without any blank or specific characters. Let me know if the issue still there.

Best!

Your sincerely,

Jianhong Ou

**Comment by mdozmorov** [comment]
Thanks, Jianhong. My understanding, the names you mentioned are the `name` slots in the `pfm` objects. It helped, although using brute force - by renaming the motifs in the original PWM file. 

I had an issue with the following:
```
pfms1 <- mapply(names(pfms1), pfms1, FUN=function(.ele, .pfm){
  new("pfm",mat=.pfm, name=.ele)}
               ,SIMPLIFY = FALSE)
Error in .local(.Object, ...) : mat must be a numeric matrix
```
I checked the `mat` slot, it is a numeric matrix. That's a separate issue though, the main issue is solved. Thanks again!
