### ISSUE TITLE
图片中motif名称后面的RC是什么意思

### ISSUE THREAD

**Issue by ilead-cong** [jianhong/motifStack#15]
![微信图片_20231116160012](https://github.com/jianhong/motifStack/assets/58165829/24590681-dc2f-4c28-acbb-954459722304)

图片中motif名称后面的RC是什么意思，是有什么特殊含义吗？

**Comment by jianhong** [comment]
ReverseComplement

**Comment by ilead-cong** [comment]
okok，谢谢
