### ISSUE TITLE
Question about the plotMotifStackWithPhylog

### ISSUE THREAD

**Issue by yanyew** [jianhong/motifStack#19]
Hello, thanks for developing this functional tools!
Here I met some problems while using motifstack to plot motifs with `layout="phylog"` or `layout="radialPhylog"`. It seems that motifstack will automatically reverse complement the motifs, which didn't meet my expectations. I checked the manual but can't find how to stop the automatically RC. I wonder that is it possible to do that?
Thank you!

**Comment by jianhong** [comment]
Thanks for trying motifStack. Did you try to set `revcomp=FALSE` when you run `motifStack` ?

**Comment by yanyew** [comment]
> revcomp=FALSE

Thanks for your quick reply!
I didn't aware of this parameter before. Now I try to run `motifStack(motifs,layout="radialPhylog",font="Arial",revcomp=FALSE)`, but the return is: `Error in DNAmotifAlignment(pfms, revcomp = revcomp) :  length of revcomp and pfms is not identical`. And I have no idea. The motifStack version is 1.42.0.

**Comment by yanyew** [comment]
> Thanks for trying motifStack. Did you try to set `revcomp=FALSE` when you run `motifStack` ?

Thanks for your quick reply!
I didn't aware of this parameter before. Now I try to run `motifStack(motifs,layout="radialPhylog",font="Arial",revcomp=FALSE)`, but the return is: `Error in DNAmotifAlignment(pfms, revcomp = revcomp) :  length of revcomp and pfms is not identical`. And I have no idea. The motifStack version is 1.42.0.

**Comment by jianhong** [comment]
Sorry, try
```{r}
motifStack(motifs,layout="radialPhylog",font="Arial",revcomp=rep(FALSE, length(motifs)))
```

**Comment by yanyew** [comment]
> Sorry, try
> 
> ```
> motifStack(motifs,layout="radialPhylog",font="Arial",revcomp=rep(FALSE, length(motifs)))
> ```

I tried, and this time the returned messages is `Error in if (any(alphab) & revcomp) { : the condition has length > 1`

I imported the pfms using `motifs<-importMatrix(dir(file.path("F:/DAP-seqv3/motif_filtered/pfm/95"),".rev.pfm$", full.names = TRUE))`

**Comment by jianhong** [comment]
Thank you for reporting this. I will fix this bug soon.

**Comment by jianhong** [comment]
I think I fixed this issue someday. Could please update the package to newest version by 
```{r}
BiocManager::install('jianhong/motifStack')
```
and try again?

**Comment by yanyew** [comment]
> I think I fixed this issue someday. Could please update the package to newest version by
> 
> ```
> BiocManager::install('jianhong/motifStack')
> ```
> 
> and try again?

Yes, it worked. Thank you!
