### ISSUE TITLE
the plot function can not combine with R layout

### ISSUE THREAD

**Issue by huijfeng** [jianhong/motifStack#4]
hi I am trying to plot a barplot under the sequence logo generated using the plot function by dividing the plot using layout, it worked fine with the old version. but now it is not working. Is there anything changed in the new version? thanks!

**Comment by jianhong** [comment]
Yes. From last release version, I updated the trackViewer to plot the figure under grid to avoid the error of mixing plot platform, which in turn caused the issue that it is not compatible with layout. Please try to use grid viewport instead. 
In the future, I am planning to address this issue. However I can not promise the schedule yet. Thank you for your comments.

Jianhong.
