### ISSUE TITLE
couple issues for RNA motifs

### ISSUE THREAD

**Issue by nmukherjee** [jianhong/motifStack#5]
I think your software is really cool. I just had a couple of questions for making a sequence logo stack plot for RNA sequences.

1. I was wondering how to prevent reverse complementation when using the `motifStack` function. Since RNA is stranded and already in a fixed orientation,  the reverse complementing is a problem.
2. I get the following  error when I try to make the  "T"  a "U" `rownames(test)[4] <- "U"`

> Error in .normargPfm(x) : 
>   invalid PFM 'x': row names must be in 'DNA_ALPHABET'

**Comment by ckntav** [comment]
The software is easy to handle and provides nice visualization. I'm am also interested in preventing reverse complementation while using `motifStack`.

A feature I like in that function is that positions are aligned between different motifs.
But I'm am wondering how to prevent clustering and distance calculation... (+ reverse complementation)
So motifs would appear in the order of my list of pcm, with aligned position and without reverse complementation.

Is there a way to do this using the underlying functions?

Thanks for providing this tool

edit:
I find a way to do what I want:
- apply `pcm2pfm` to my list of pcm
- align with `DNAmotifAlignment` with revcomp = FALSE
- choose the order of my motifs by providing a vector to my list of alignment
- plot with `plotMotifLogoStack` by providing the ordered output of DNAmotifAlignment

**Comment by jianhong** [comment]
Hi nmukherjee,

I add new function called DNAmotifToRNAmotif in the development version. Also, I set revcomp into FALSE for RNA motifs when calling motifStack.

It will be released in the coming weeks.

Jianhong.


> I think your software is really cool. I just had a couple of questions for making a sequence logo stack plot for RNA sequences.
> 
> 1. I was wondering how to prevent reverse complementation when using the `motifStack` function. Since RNA is stranded and already in a fixed orientation,  the reverse complementing is a problem.
> 2. I get the following  error when I try to make the  "T"  a "U" `rownames(test)[4] <- "U"`
> 
> > Error in .normargPfm(x) :
> > invalid PFM 'x': row names must be in 'DNA_ALPHABET'

**Comment by jianhong** [comment]
Hi ckntav,

I set revcomp into FALSE for RNA motifs when calling motifStack.
I add new pcm2pfm methods for list.
I reorder parameter to motifStack function. You can try to set it into FALSE to keep the input order.

Jianhong.

> The software is easy to handle and provides nice visualization. I'm am also interested in preventing reverse complementation while using `motifStack`.
> 
> A feature I like in that function is that positions are aligned between different motifs.
> But I'm am wondering how to prevent clustering and distance calculation... (+ reverse complementation)
> So motifs would appear in the order of my list of pcm, with aligned position and without reverse complementation.
> 
> Is there a way to do this using the underlying functions?
> 
> Thanks for providing this tool
> 
> edit:
> I find a way to do what I want:
> 
> * apply `pcm2pfm` to my list of pcm
> * align with `DNAmotifAlignment` with revcomp = FALSE
> * choose the order of my motifs by providing a vector to my list of alignment
> * plot with `plotMotifLogoStack` by providing the ordered output of DNAmotifAlignment

**Comment by ckntav** [comment]
Thank you for the enhancements of the tool,

Chris
