### ISSUE TITLE
method argument of matAlign is ignored

### ISSUE THREAD

**Issue by bpolacco** [jianhong/motifStack#9]
I just found this package today, and looks like it has some nice useful functionality.  I found a small--and probably easy to fix--problem in one of the functions:

matalign function has an argument `method`.  If the user sets this to "Needleman-Wunsch" it has no effect, and the default SW method is used.  This appears to be because the `method` argument is not passed to the downstream function `compareProfiles`

**Comment by jianhong** [comment]
Thank you for reporting that. I will fix it as soon as possible.
